pulumi/scripts

- ci/check-worktree-is-clean
- ci/ensure-dependencies
- ci/install-common-toolchain.sh
- ci/prepare-environment.sh
- ci/upload-failed-tests
Take `pulumi/pulumi`'s scripts that are used in CI and share them
here. We'll move to a model where travis clones this repository and
then invokes these scripts directly, instead of having each repository
have to clone a bunch of logic around how to install toolchains, what
versions of things to install and the like.
> Check in shared travis scripts

- ci/install-common-toolchain.sh
On some of the travis workers, it looks like the apt-get cache does
not contain pandoc, and so an explicit `apt-get update` is required
before trying to install pandoc.
> Run `apt-get update` before installing pandoc

- hack-vendor/cmd/change-constraint/main.go
- hack-vendor/cmd/vendor-git-server/main.go
- hack-vendor/hack-vendor
`hack-vendor` is a small script that makes it quick to override a
vendored dependency (managed by `dep`) with a local version. It works
by spinning up a local web server that exposes $GOPATH/src and then
modifies the `Gopkg.toml` file of a project to override the source of
the package you want to modify to point at this local server and does
a restore.
The web-server listens on port 80, due to limitiations with `dep` when
this script was authored. It appears that newer versions would allow
sources to actually have a non standard port, so in the future we may
be able to modify the scripts to just have the web-server listen on
some non standard port, which would prevent the need to sudo.
> Open source `hack-vendor`

- ci/install-common-toolchain.sh
We have started seeing failures in `pulumi/pulumi` on macOS with:
```
$ source ./build/travis/install-common-toolchain.sh
Downloading and installing node v6.10.3...
Downloading https://nodejs.org/dist/v6.10.3/node-v6.10.3-darwin-x64.tar.xz...
Computing checksum with shasum -a 256
Checksums matched!
Now using node v6.10.3 (npm v3.10.10)
ln: /usr/local/bin/pip: File exists
```
This seems like a reasonable fix. Since we don't control the Travis environment, perhaps this was a bug that was "fixed" which in-turn broke our workaround.
> Don't create symlink if it already exists

- ci/add-plugin-installer-script.js
- ci/install-pulumi-plugin.js
- ci/publish-tfgen-package
This change extracts the shared logic we have duplicated in every
terraform based provider repository into a common location.
In addition, it augments the publishing scripts to support
pulumi/pulumi#2155.
Previously, the poorly named `promote.js` would rewrite the
`package.json` of a package before we were going to publish it. It
would add an `install` script to the `scripts` section of package.json
which called `pulumi plugin install resource <name> <version>` so that
when packages were restored, the plugin would be installed.
However, when installing on a machine where `pulumi` was not present,
this script would fail and cause the entire `npm install` or `yarn
install` to fail because `pulumi` could not be run.
Now, instead of invoking pulumi directly, we invoke a script which
ships …
> Adopt new node installer scripts

- ci/run-at-head
The intention of this new script is to allow us to run our node tests
"at HEAD". When run, this script does a few things:
1. For every `@pulumi` package, figure out the latest version, by
looking at what the `dev` tag points at.
2. Install the latest dev build of the CLI (i.e. the one that matches
the "dev" tag of @pulumi/pulumi).
3. Set an environment variaible that has information about the latest
versions of all the packages.
4. Call `make travis_${TRAVIS_EVENT_TYPE}` like a normal Travis build
would.
The integration tests in each repository will use the environment
variable that we've set to pass information about the latest versions
to the integration test framework, to ensure we use the newest
versions.
> Add a script for testing "at HEAD"

- hack-vendor/cmd/change-constraint/main.go
Just what it says on the tin. Previously the tool was dropping all
constriants.
> Only drop conflicting constraints in change-constraint

- hack-vendor/cmd/change-constraint/main.go
Just what it says on the tin. dep fails to parse the TOML otherwise.
> Omit empty constraints in change-constraint

- govendor-override/main.go
`govendor-override` is designed to _exactly_ match the dependency versions specified by an upstream Terraform provider when resolving dependencies for a Pulumi resource provider based upon it.
Unfortunately, we misinterpreted the semantics of `dep` when a semantic version is specified, and as such were pinning to a major version, but not an exact version. For a long time, semantic versioning worked as designed and we didn't see an breakage with this, but terraform-providers/terraform-provider-aws#6806 saw a regression in an upstream library meaning pinning to the exact version of the AWS SDK specified by upstream is required.
According to the dep docs:
> When you specify a version without an operator, dep automatically uses the ^ operator by default. dep ensure will interpret the given …
> Target exact versions in `govendor-override`

- ci/install-common-toolchain.sh
This ensures broad availability of `tf2pulumi`, which is now used
to generate examples in our documentation, from Terraform packages.
> Install tf2pulumi in the common toolchain

- ci/check-package-dependencies
- ci/publish-tfgen-package
We want to ensure that when we publish a package, none of the
dependencies are pre-release dependencies (which we, for better or
worse, end up using often during cross cutting development across our
many repositories).
This change adds a new script, `check-package-dependencies` that will
run validation logic against the package.json we are about to publish
and use its exit code to communicate if the package should be
published or not.
Our shared publishing script uses this a pre-check before actually
doing the publish.
> Add policy checks for packages before publishing

- ci/install-common-toolchain.sh
Not having tf2pulumi available with late versions of pulumi-terraform gives diffs which remove all the docs - better to install it by default so we can make progress in other repos.
> Enable installation of tf2pulumi in CI

- ci/install-common-toolchain.sh
This allows the script to proceed normally on Ubuntu outside of Travis CI without needing additional environment variables to be set.
> Test OS instead of TRAVIS_OS_NAME when installing

- ci/install-common-toolchain.sh
This upgrades as discussed to `dep` 0.5.0. Obviously this will break downstream builds when merged, so probably best to wait until everything is lined up to go and downstream PR builds can be retriggered after this has been merged.
> Upgrade to dep 0.50

- ci/install-common-toolchain.sh
install-common-toolchain.sh is defining and setting OS from within a
subshell while also referencing that variable in the parent shell. The
writes to the OS variable from within the subshell are not visible in
the parent shell and, as a result, we were not putting Python's bin
directory on the PATH on OSX.
This fixes the issue by defining OS in the parent shell and exporting
it, so that it's visible in the subshell and in the parent shell.
> Calculate and set OS from outside of the subshell

- gomod-override/main.go
- gomod-override/template.go
- gomod-override/testdata/Gopkg-aws-1.57.0.template.toml
Versions like `0.11.1-beta1` have a prerelease tag, but not one of the form `date-SHA` as used by modules to specify exact revisions. If we detect this, we should use the whole version string instead of attempting to extract a SHA.
> Make gomod-override work for terraform-provider-aws v1.57.0

- ci/install-common-toolchain.sh
Hopefully we can track the version of Pandoc in `brew` in CI (since installing from the Mac OS packages is awkward). Using the same version in CI should reduce the number of spurious whitespace diffs causing CI to fail for some providers.
> Use a specific build of Pandoc in CI

- gomod-override/dependency.go
Unfortunately some module dependencies still refer to HTTP paths without TLS - `go get` does not allow that without the `-insecure` flag, so allow that to be set if necessary.
> Allow opting into insecure downloads via go get if absolutely necessary

- gomod-doccopy/README.md
- gomod-doccopy/main.go
Go modules can be used in a mode which populate a `vendor/` directory inside a repository in a `GOPATH`, preserving much of the workflow of tools such as `dep`. Unfortunately, it only copies Go files from packages needed to build.
For bridged Terraform providers, we also need the `website/` directory present in order to create documentation.
This tool recursively copies the `website/` directory from the machine module cache (which represents a complete version of the repository) to the appropriate spot in the `vendor` directory for a given Terraform provider.
_This is definitely not a pull request I am particularly proud of, but all of the advice I have seen is that this is the only way to use `go mod vendor` and have non-Go files copied in, and a tool specialised to our narrow usage …
> Add gomod-doccopy tool

- gomod-doccopy/main.go
Unfortunately it isn't sufficient to copy just the website/ directory when building terraform bridged providers - rather than try to enumerate everything needed, it's simpler to copy the entire repository into the vendor directory.
> Copy all provider files in gomod-doccopy

- ci/install-common-toolchain.sh
This should save a few seconds per build for something we're not using any more.
> Remove go-metalinter from CI toolchain

- gomod-doccopy/README.md
- gomod-doccopy/main.go
This approach for handling replaced module is required less user input, and is more correct than the (reverted) approach taken previously - instead of specifying source and destination organizations, we read the entire replacement from the modules.txt file and use that where appropriate.
This is necessary for when we replace import paths with forks of providers (e.g. AWS, Azure).
In order to make progress elsewhere I'll merge this pending CI, and address any issues post-hoc.
> Handle module replacement in gomod-doccopy

- gomod-override/dependency.go
Serveral of our upstreams now have a dependency on a Bazaar repository. Since it's pinned to a specific revision, this looks like a short Git SHA which we try to resolve using `go get` before finding the complete SHA. If we can't open the repository resulting from `go get`, we should use the SHA component as is, since it likely refers to another VCS revision identifier.
> Use unmodified version for non-Git repositories

- gomod-doccopy/main.go
This allows `gomod-doccopy` to deal with module replacements with local paths.
> Deal with local module replacement syntax in gomod-doccopy

- ci/publish-tfgen-package
`pulumi/pulumi-terraform` uses the `tfgen` layout for it's SDK but does not have a Python package yet (as Read is not supported in Python yet). This change allows us to skip attempts to publish a package for Python but still use the remaining parts of the `tfgen` publishing script.
> Allow opting out of publishing a python package

- ci/publish-tfgen-package
This `if` statement was the wrong way around - we should skip only if a value is set.
> Invert check for skipping Python packages

- ci/publish-tfgen-package
Since we use the existence of NO_TFGEN_PYTHON_PACKAGE to indicate that we want to skip a Python provider, having option `nounset` on causes problems - according to ShellCheck we're ok here, so this commit removes that option from the script, fixing package builds for providers which do _not_ opt out of Python support.
Note that this is what is causing the build failure for GCP, currently.
> Remove -o nounset from tfgen publishing script

- update-pulumi-terraform/update-pulumi-terraform.sh
This commit adds a bash script which can be used for updating `pulumi-terraform` to the latest commit across all Terraform-backed providers, with an optional CHANGELOG notice being added to each repo.
Note the following dependencies:
- Go on `PATH`
- Git on `PATH`, and an SSH key in the local agent
- Hub on `PATH`, and logged in to GitHub
- `jq` on `PATH`
- `curl` on `PATH`
We also assume the local machine is configured with appropriate author details for Git commits.
> Add script to update pulumi-terraform across repos

- ci/run-at-head
1. Add `--no-latest-cli` and `--no-latest-packages` as way to control
if the latest CLI or Packages are used during the run. This lets us
mix and match things like "current set of packages with dev CLI" and
"current released CLI with latest dev packages"
2. Remove Python overrides stuff. Sean added this code in the past but
nothing actually uses it. The list of packages is no longer complete
and rather than bringing it up to date, I'm just removing it for now.
3. Expand the list of nodejs packages we compute the latest versions
for. I computed this list by looking at the `@pulumi` scope on NPM,
removing any private packages.
> `run-at-head` improvements

- ci/build-package-docs.sh
These changes add a new script that clones
https://github.com/pulumi/docs, regenerates the appropriate parts of the
docs site, and opens a pull request with the changes. Documentation will
only be regenerated for commits that have an appropriate tag. This
script should be run after packages have been published, and should be
run as part of the same job that performed the build.
> Add a script for building package docs.

- ci/build-package-docs.sh
- Require PULUMI_BOT_GITHUB_API_TOKEN
- Explain how to trigger a new docs build if the script fails
> Improve the build-package-docs script

- ci/ensure-dependencies
- ci/install-common-toolchain.sh
- ci/show-elapsed-time
Pulumi itself now requires Python 3 and Python 2.7 will be EOL
shortly.  Let's explicitly request `python3` and `pip3`.
Contributes To: #37
> Use Python 3 in our infrastructure scripts

- ci/install-common-toolchain.sh
This is to aid debugging in `pulumi-vault` which seems to be claiming that Python 3.6.7 is not available in Travis anymore, but is useful generally and should not unduly delay builds
> List pyenv versons before selecting one

- ci/install-common-toolchain.sh
Node 8 is EOL, and some dependencies no longer support it.
Part of pulumi/pulumi#3732.
> Use Node 10 by default

- ci/publish-tfgen-package
We currently detect `feature/XXX` branches, which we use to make npm tags like `feature-xxx`.  This works well except for one significant problem.
Specifically, because of https://github.com/golang/go/issues/30851 we are unable to reference these feature branches using go modules.  This is problematic as there's no easy way to then have downstream repos (like `@pulumi/aws`) reference the latest built version from this branch.  While we can reference teh package by commit, that's much more error prone and difficult to manage.
This PR simply allows us to actually write our branches like `feature-xxx` instead of just `features/xxx`.  This is actually simpler as we simply use that branch name as is instead of having to convert it to this form (like we do with `features/xxx`=>`feature-xxx`). …
> Detect feature branches written with a different format

- ci/install-common-toolchain.sh
Start using .NET Core SDK 3.1. 3.0 is end of life within 1 month from now.
Steps described in https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804
> Update .NET Core SDK to 3.1

- ci/install-common-toolchain.sh
This commit prevents changes to `go.mod` resulting from installing tools via `go get` when in a module path outside of GOPATH, by explicitly disabling modules for these operations.
This addresses the type of failure seen in pulumi/pulumi-vault#29, and should not impact other types of job.
> Set `GO111MODULE=off` when getting ancillary tools

- ci/publish-github-release.sh
Fixes: https://github.com/pulumi/pulumi/issues/3167
Currently we only deploy tags - we should also publish the release
within github as well since this will allow people to subscribe to
the releases
> Publish GitHub release

- ci/run-at-head
We are going to default the testing framework to the beta Pulumi
packages. Nothing in the framework was changed, therefore we don't
even need to do this, the standard `make ensure` will install the
correct go mod
This means we won't ever get into this weird situation of trying to
install a module that isn't a v2 when it should be
This has also been broken since we upgraded to go modules in the
Pulumi repo as we now have SDK and PKG rather than just pulumi as
a whole
> Remove GO GET for specific version of Pulumi

- ci/build-package-docs.sh
I have no idea what I'm talking about, so please double check my work here.
----
We want to build the resource docs (`gen_resource_docs.sh` in the `docs` repo) as part of running `ci/build-package-docs.sh`. @praneetloke actually did the work to parameterize this file in https://github.com/pulumi/docs/pull/2820:
> I also updated the gen_resource_docs.sh script to accept a provider name override to generate docs for a single provider, which is required for CI scenarios when we release a new provider. [This commit](https://github.com/pulumi/docs/pull/2820/commits/24037853eebd8518e5f3dde626b2a257a94f4251) has those changes. We are not yet ready to make the upstream script changes to make use of this (though I expect it to work). My main motivation for doing this is for my local development …
> Call gen_resource_docs.sh when building package

- ci/build-package-docs.sh
Related to https://github.com/pulumi/docs/issues/2785.
Now that we have added the `generate_schema` `Makefile` target for both `aiven` and `mailgun`, we can generate resource docs for those as well.
> Remove aiven and mailgun from list of excluded repos for generating resource docs

- ci/build-package-docs.sh
Fixes #111.
Now that the `generate_python_docs.sh` script supports passing the package name to generate docs for, we can make use of that when making provider releases.
> Pass the package name when generating Python docs.

- ci/build-package-docs.sh
The last time I tagged a release in the `pulumi/pulumi-policy` repo, after publishing the packages, when attempting to open the docs PR, the build failed with:
```
$(go env GOPATH)/src/github.com/pulumi/scripts/ci/build-package-docs.sh policy
Building SDK docs for version 1.1.0:
fatal: destination path '/home/travis/gopath/src/github.com/pulumi/pulumi' already exists and is not an empty directory.
Makefile:12: recipe for target 'publish_packages' failed
make: *** [publish_packages] Error 128
```
The problem is this script is now trying to clone `pulumi/pulumi`, but in the case of the `pulumi-policy` repo, the `pulumi/pulumi` repo directory already exists, so the git clone fails.
As far as I can tell, the `pulumi/pulumi-policy` repo doesn't explicitly clone the `pulumi/pulumi` repo, but it …
> Clone `pulumi/pulumi` only if the directory doesn't exist

- ci/configure-aws.sh
Add a new `ci/configure-aws.sh` script to the Pulumi scripts repo. This will allow us to leverage the AWS SDK for switching between IAM Roles, and provides some useful Bash functions for the situations when we can't.
Today we just set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables in most of the provider repos for running unit tests. The AWS SDK then will use those environment variables to authenticate access, e.g. when we run `pulumi up`, `aws s3`, etc.
As we move to a slightly different topology of AWS accounts and access, this is problematic.
Rather than giving our CI/CD workers long lived credentials with broad access, we are moving to a world where they have very limited access and need to assume specific roles to run tests. (e.g. gain access to the …
> Add configure-aws.sh

- ci/configure-aws.sh
Evidently `~/.aws` isn't created when you install the AWS CLI. And trying to write a file into a directory that doesn't exist "isn't a good idea".
> Create ~/.aws folder if needed

- ci/configure-aws.sh
`AWS_SECURITY_TOKEN` is not an env var that is used by the AWS SDK. This should instead be `AWS_SESSION_TOKEN`, which coincides with the property name used in the output of `aws sts assume-role` called `SessionToken`.
> Set AWS_SESSION_TOKEN instead of AWS_SECURITY_TOKEN in configure-aws.sh

- ci/build-package-docs.sh
Exclude python doc generation for TS-only packages: awsx, eks, kx, and terraform
> Exclude python doc generation for TS-only packages

- ci/install-common-toolchain.sh
dep is no longer needed in the common toolchain since
all of the providers have moved to go modules
> Remove dep and bump pulumictl to 0.0.5

- ci/install-common-toolchain.sh
`nvm` needs to export variables into the parent shell, and it can't do
that when it's invoked in a subshell.
> Install node outside the subshell.

- ci/publish-tfgen-package
With work like https://github.com/pulumi/pulumi-kubernetes/pull/2501 once a project is building wheels from a Pyproject.toml it might make sense to also send them to PyPI using twine. Adding some opt-in configurations here to send wheels, or both wheels and tar.gz.
> Allow opting into sending wheels to PyPI
